version: '3.8'

services:
  app:
    build:
      context: .
    image: satyam0510/vitasource:v1
    container_name: vitasource-app
    restart: unless-stopped
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - vitasource-net
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pharmacy_db
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: vitasource-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmacy_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - vitasource-net

networks:
  vitasource-net:
    driver: bridge
